apiVersion: v1
kind: Service
metadata:
  name: "www-{{ .Values.app.name }}"
  namespace: {{ .Values.app.namespace }}
spec:
  type: ClusterIP
  selector:
    app: "www-{{ .Values.app.name }}"
  ports:
    - name: www
      protocol: TCP
      port: 80
      targetPort: 80